version: "2"

services:
  mongo:
    image: centos/mongodb-32-centos7@sha256:3a6588194d61d03b19401247b82405ef94a417efae0bfc21f67bf517a59b861d
    environment:
      - MONGODB_USER=userS1H
      - MONGODB_PASSWORD=14tHhw1FjcP42Xiy
      - MONGODB_DATABASE=modeling
      - MONGODB_ADMIN_PASSWORD=14tHhw1FjcP42Xiy
    networks:
      - beagleml
    ports:
      - "27017:27017"

  kafka:
    image: spotify/kafka@sha256:cf8f8f760b48a07fb99df24fab8201ec8b647634751e842b67103a25a388981b
    environment:
      - ADVERTISED_PORT=9092
      - ADVERTISED_HOST=kafka
    networks:
      - beagleml
    ports:
      - "2181:2181"
      - "9092:9092"
      
  beagleml-monitor:
    image: bbvalabs/beagleml-monitor:1.0.0@sha256:d15cd578b5e35dfefc46ce2c156cca6e8b359e0b4b9fe5a55983b07cf4916abd
    command: ./start.sh
    environment:
      - LOG_CONFIG_FILE=logging.yaml
      - MAIN_TOPIC=scheduler-monitor
      - KAFKA_SERVERS=kafka
      - KAFKA_GROUP=1
      - MONGO_URL=mongo
      - MONGODB_DATABASE=modeling
      - MONGODB_USER=userS1H
      - MONGODB_PASSWORD=14tHhw1FjcP42Xiy
      - MONGO_PORT=27017
    networks:
      - beagleml
    depends_on:
      - kafka
      - mongo

networks:
  beagleml:
    driver: bridge
