#!/bin/bash

LOG_CONFIG_FILE="../src/logging.yaml"
MAIN_TOPIC="scheduler-monitor"
KAFKA_SERVERS="172.30.23.3"
#kube: 10.42.17.202:9092
#cattle: 10.41.35.153
KAFKA_GROUP=""
MONGO_URL="172.30.23.2"
# MONGO_PORT="27017"
DB_NAME="beagleml"
# rancher kube: beaglemlDB
DB_USER="user0LT"
DB_PWD="P4fQMKF7yERFddXu"


LOG_CONFIG_FILE=$LOG_CONFIG_FILE MAIN_TOPIC=$MAIN_TOPIC KAFKA_SERVERS=$KAFKA_SERVERS KAFKA_GROUP=$KAFKA_GROUP MONGO_URL=$MONGO_URL MONGO_PORT=$MONGO_PORT DB_NAME=$DB_NAME DB_USER=$DB_USER DB_PWD=$DB_PWD \
        python -u ../src/main.py
