version: 1
formatters:
  simple:
    format: '%(asctime)s %(levelname)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: "/var/log/beagleml-monitor.log"
  error:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stderr
loggers:
  mainLogger:
    level: DEBUG
    handlers: [console, file, error]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
